# Generated by Django 5.0.8 on 2024-09-02 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='participants',
            field=models.ManyToManyField(through='expenses.Participant', to='expenses.user'),
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='payer_expenses', to='expenses.user'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('expense', 'user')},
        ),
    ]
