# Generated by Django 5.0.8 on 2024-09-04 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_remove_expense_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='user',
            new_name='payer',
        ),
    ]
